function create_line_bisection_files_v2()
% Creates a clean, updated version of the line bisection experiment.
%
% Features:
% - No Psychtoolbox required
% - MATLAB figures only
% - Individual condition
% - Shared host/client condition using TCP/IP
% - Robust data-folder creation
% - Trial-by-trial CSV saving
% - Keyboard-only input handling
% - Mouse/touchpad ignored
% - Valid responses require + or -
% - Backspace allowed
% - Enter confirms response
% - Escape aborts safely
% - Shared condition records who triggered each trial

writeFile('make_trial_orders.m', make_trial_orders_code());
writeFile('run_line_bisection_individual.m', individual_code());
writeFile('run_line_bisection_shared_host.m', host_code());
writeFile('run_line_bisection_shared_client.m', client_code());
writeFile('lb_draw_trial.m', draw_code());
writeFile('lb_get_response.m', response_code());
writeFile('lb_wait_for_space.m', wait_space_code());
writeFile('lb_save_row.m', save_code());

dataDir = fullfile(pwd, 'data');
if ~exist(dataDir, 'dir')
    mkdir(dataDir);
end

disp('Created updated line bisection experiment files.');
disp('Next step: run make_trial_orders.');
end

function writeFile(fname, txt)
fid = fopen(fname, 'w');
if fid < 0
    error('Could not create %s', fname);
end
fprintf(fid, '%s', txt);
fclose(fid);
end

function txt = make_trial_orders_code()
txt = [
"function orders = make_trial_orders()" newline ...
"% Fixed trial orders for all participants." newline ...
"% Individual and shared orders are different but deterministic." newline ...
"" newline ...
"positions = -900:25:900;       % 73 positions" newline ...
"positions = repmat(positions, 1, 2);  % 146 trials" newline ...
"" newline ...
"rng(20260427, 'twister');" newline ...
"orders.individual = positions(randperm(numel(positions)));" newline ...
"" newline ...
"rng(20260428, 'twister');" newline ...
"orders.shared = positions(randperm(numel(positions)));" newline ...
"" newline ...
"save('trial_orders.mat', 'orders');" newline ...
"disp('Saved trial_orders.mat');" newline ...
"end" newline ...
];
end

function txt = individual_code()
txt = [
"function run_line_bisection_individual(participantID)" newline ...
"% Individual line bisection condition." newline ...
"" newline ...
"if nargin < 1 || isempty(participantID)" newline ...
"    participantID = input('Participant ID, e.g. dyad001_A: ', 's');" newline ...
"end" newline ...
"" newline ...
"if ~exist('trial_orders.mat', 'file')" newline ...
"    make_trial_orders();" newline ...
"end" newline ...
"load('trial_orders.mat', 'orders');" newline ...
"trials = orders.individual;" newline ...
"" newline ...
"dataDir = fullfile(pwd, 'data');" newline ...
"if ~exist(dataDir, 'dir')" newline ...
"    mkdir(dataDir);" newline ...
"end" newline ...
"outfile = fullfile(dataDir, [participantID '_individual.csv']);" newline ...
"" newline ...
"fig = figure('Color','k','MenuBar','none','ToolBar','none','NumberTitle','off', ..." newline ...
"    'Name','Line Bisection - Individual');" newline ...
"set(fig, 'WindowState', 'maximized');" newline ...
"drawnow;" newline ...
"" newline ...
"try" newline ...
"    for t = 1:numel(trials)" newline ...
"        truePos = trials(t);" newline ...
"" newline ...
"        clf(fig);" newline ...
"        set(fig,'Color','k');" newline ...
"        text(0.5,0.5,sprintf('Trial %d of %d\n\nPress SPACE to start',t,numel(trials)), ..." newline ...
"            'Color','w','HorizontalAlignment','center','FontSize',24,'Units','normalized');" newline ...
"        axis off; drawnow;" newline ...
"" newline ...
"        lb_wait_for_space(fig);" newline ...
"" newline ...
"        lb_draw_trial(fig, truePos, '');" newline ...
"        [resp, rtFirst, rtEnter, editTime] = lb_get_response(fig, truePos, true);" newline ...
"" newline ...
"        iti = 0.3 + rand()*0.2;" newline ...
"        timestamp = datetime('now');" newline ...
"" newline ...
"        row = table({participantID}, {'individual'}, t, truePos, resp, resp-truePos, ..." newline ...
"            rtFirst, rtEnter, editTime, iti, {''}, timestamp, ..." newline ...
"            'VariableNames', {'participantID','condition','trial','truePosition','response','error', ..." newline ...
"            'RT_firstKey','RT_enter','editingTime','ITI','triggeredBy','timestamp'});" newline ...
"" newline ...
"        lb_save_row(outfile, row);" newline ...
"" newline ...
"        clf(fig); set(fig,'Color','k'); axis off; drawnow;" newline ...
"        pause(iti);" newline ...
"    end" newline ...
"" newline ...
"    clf(fig);" newline ...
"    set(fig,'Color','k');" newline ...
"    text(0.5,0.5,'Finished. Thank you.','Color','w','HorizontalAlignment','center','FontSize',28,'Units','normalized');" newline ...
"    axis off; drawnow;" newline ...
"" newline ...
"catch ME" newline ...
"    if isvalid(fig)" newline ...
"        close(fig);" newline ...
"    end" newline ...
"    rethrow(ME);" newline ...
"end" newline ...
"end" newline ...
];
end

function txt = host_code()
txt = [
"function run_line_bisection_shared_host(dyadID, participantID, port)" newline ...
"% Shared condition: HOST computer." newline ...
"" newline ...
"if nargin < 1 || isempty(dyadID); dyadID = input('Dyad ID, e.g. dyad001: ', 's'); end" newline ...
"if nargin < 2 || isempty(participantID); participantID = [dyadID '_A']; end" newline ...
"if nargin < 3 || isempty(port); port = 50000; end" newline ...
"" newline ...
"if ~exist('trial_orders.mat', 'file'); make_trial_orders(); end" newline ...
"load('trial_orders.mat', 'orders');" newline ...
"trials = orders.shared;" newline ...
"" newline ...
"dataDir = fullfile(pwd, 'data');" newline ...
"if ~exist(dataDir, 'dir')" newline ...
"    mkdir(dataDir);" newline ...
"end" newline ...
"localFile = fullfile(dataDir, [participantID '_shared.csv']);" newline ...
"syncFile  = fullfile(dataDir, [dyadID '_shared_sync.csv']);" newline ...
"" newline ...
"disp(['Starting TCP server on port ' num2str(port)]);" newline ...
"srv = tcpserver('0.0.0.0', port, 'Timeout', 60);" newline ...
"configureTerminator(srv, 'LF');" newline ...
"disp('Waiting for client connection...');" newline ...
"while srv.Connected == 0" newline ...
"    pause(0.1);" newline ...
"end" newline ...
"disp('Client connected.');" newline ...
"writeline(srv, 'HELLO_FROM_HOST');" newline ...
"" newline ...
"fig = figure('Color','k','MenuBar','none','ToolBar','none','NumberTitle','off', ..." newline ...
"    'Name','Line Bisection - Shared Host');" newline ...
"set(fig, 'WindowState', 'maximized'); drawnow;" newline ...
"" newline ...
"try" newline ...
"    for t = 1:numel(trials)" newline ...
"        truePos = trials(t);" newline ...
"" newline ...
"        clf(fig); set(fig,'Color','k');" newline ...
"        text(0.5,0.5,sprintf(['Trial %d of %d\n\nYou and your partner will see the same line.\n' ..." newline ...
"            'Work silently and enter only your own estimate.\n\nEither participant may press SPACE to start.'], ..." newline ...
"            t, numel(trials)), 'Color','w','HorizontalAlignment','center','FontSize',22,'Units','normalized');" newline ...
"        axis off; drawnow;" newline ...
"" newline ...
"        triggeredBy = waitForSharedStartHost(fig, srv);" newline ...
"        trialStartTime = datetime('now');" newline ...
"        writeline(srv, sprintf('START|%d|%d|%s', t, truePos, triggeredBy));" newline ...
"" newline ...
"        lb_draw_trial(fig, truePos, '');" newline ...
"        [resp, rtFirst, rtEnter, editTime] = lb_get_response(fig, truePos, true);" newline ...
"        localDoneTime = datetime('now');" newline ...
"        writeline(srv, sprintf('DONE|%d|HOST', t));" newline ...
"" newline ...
"        waitForClientDone(srv, t);" newline ...
"        bothDoneTime = datetime('now');" newline ...
"" newline ...
"        iti = 0.3 + rand()*0.2;" newline ...
"" newline ...
"        row = table({participantID}, {'shared'}, t, truePos, resp, resp-truePos, ..." newline ...
"            rtFirst, rtEnter, editTime, iti, {triggeredBy}, localDoneTime, ..." newline ...
"            'VariableNames', {'participantID','condition','trial','truePosition','response','error', ..." newline ...
"            'RT_firstKey','RT_enter','editingTime','ITI','triggeredBy','timestamp'});" newline ...
"        lb_save_row(localFile, row);" newline ...
"" newline ...
"        syncRow = table({dyadID}, t, truePos, {triggeredBy}, trialStartTime, bothDoneTime, iti, ..." newline ...
"            'VariableNames', {'dyadID','trial','truePosition','triggeredBy','trialStartTime','bothDoneTime','ITI'});" newline ...
"        lb_save_row(syncFile, syncRow);" newline ...
"" newline ...
"        writeline(srv, sprintf('ITI|%.3f', iti));" newline ...
"        clf(fig); set(fig,'Color','k'); axis off; drawnow;" newline ...
"        pause(iti);" newline ...
"    end" newline ...
"" newline ...
"    writeline(srv, 'FINISHED');" newline ...
"    clf(fig); set(fig,'Color','k');" newline ...
"    text(0.5,0.5,'Finished. Thank you.','Color','w','HorizontalAlignment','center','FontSize',28,'Units','normalized');" newline ...
"    axis off; drawnow;" newline ...
"" newline ...
"catch ME" newline ...
"    try" newline ...
"        writeline(srv, 'ABORT');" newline ...
"    catch" newline ...
"    end" newline ...
"    if isvalid(fig)" newline ...
"        close(fig);" newline ...
"    end" newline ...
"    rethrow(ME);" newline ...
"end" newline ...
"end" newline ...
"" newline ...
"function triggeredBy = waitForSharedStartHost(fig, srv)" newline ...
"% Waits for SPACE on host or SPACE request from client." newline ...
"% Ignores mouse/touchpad input." newline ...
"" newline ...
"triggeredBy = '';" newline ...
"abortTask = false;" newline ...
"set(fig, 'KeyPressFcn', @keyHandler);" newline ...
"" newline ...
"while isempty(triggeredBy)" newline ...
"    drawnow;" newline ...
"" newline ...
"    if abortTask" newline ...
"        error('Experiment aborted by HOST with ESC.');" newline ...
"    end" newline ...
"" newline ...
"    while srv.NumBytesAvailable > 0" newline ...
"        msg = char(readline(srv));" newline ...
"        if startsWith(msg, 'SPACE')" newline ...
"            triggeredBy = 'CLIENT';" newline ...
"            return;" newline ...
"        elseif startsWith(msg, 'ABORT')" newline ...
"            error('Experiment aborted by CLIENT.');" newline ...
"        end" newline ...
"    end" newline ...
"" newline ...
"    pause(0.005);" newline ...
"end" newline ...
"" newline ...
"    function keyHandler(~, event)" newline ...
"        switch event.Key" newline ...
"            case 'space'" newline ...
"                triggeredBy = 'HOST';" newline ...
"            case 'escape'" newline ...
"                abortTask = true;" newline ...
"        end" newline ...
"    end" newline ...
"end" newline ...
"" newline ...
"function waitForClientDone(srv, trialNum)" newline ...
"% Wait until client has submitted a valid response." newline ...
"while true" newline ...
"    drawnow;" newline ...
"    if srv.NumBytesAvailable > 0" newline ...
"        msg = char(readline(srv));" newline ...
"        if startsWith(msg, sprintf('DONE|%d|CLIENT', trialNum))" newline ...
"            return;" newline ...
"        elseif startsWith(msg, 'ABORT')" newline ...
"            error('Experiment aborted by CLIENT.');" newline ...
"        end" newline ...
"    end" newline ...
"    pause(0.005);" newline ...
"end" newline ...
"end" newline ...
];
end

function txt = client_code()
txt = [
"function run_line_bisection_shared_client(dyadID, participantID, hostIP, port)" newline ...
"% Shared condition: CLIENT computer." newline ...
"" newline ...
"if nargin < 1 || isempty(dyadID); dyadID = input('Dyad ID, e.g. dyad001: ', 's'); end" newline ...
"if nargin < 2 || isempty(participantID); participantID = [dyadID '_B']; end" newline ...
"if nargin < 3 || isempty(hostIP); hostIP = input('Host IP address: ', 's'); end" newline ...
"if nargin < 4 || isempty(port); port = 50000; end" newline ...
"" newline ...
"if ~exist('trial_orders.mat', 'file'); make_trial_orders(); end" newline ...
"load('trial_orders.mat', 'orders');" newline ...
"trials = orders.shared;" newline ...
"" newline ...
"dataDir = fullfile(pwd, 'data');" newline ...
"if ~exist(dataDir, 'dir')" newline ...
"    mkdir(dataDir);" newline ...
"end" newline ...
"localFile = fullfile(dataDir, [participantID '_shared.csv']);" newline ...
"" newline ...
"disp(['Connecting to host ' hostIP ':' num2str(port)]);" newline ...
"cli = tcpclient(hostIP, port, 'Timeout', 60);" newline ...
"configureTerminator(cli, 'LF');" newline ...
"pause(0.5);" newline ...
"" newline ...
"fig = figure('Color','k','MenuBar','none','ToolBar','none','NumberTitle','off', ..." newline ...
"    'Name','Line Bisection - Shared Client');" newline ...
"set(fig, 'WindowState', 'maximized'); drawnow;" newline ...
"" newline ...
"try" newline ...
"    for t = 1:numel(trials)" newline ...
"" newline ...
"        clf(fig); set(fig,'Color','k');" newline ...
"        text(0.5,0.5,sprintf(['Trial %d of %d\n\nYou and your partner will see the same line.\n' ..." newline ...
"            'Work silently and enter only your own estimate.\n\nEither participant may press SPACE to start.'], ..." newline ...
"            t, numel(trials)), 'Color','w','HorizontalAlignment','center','FontSize',22,'Units','normalized');" newline ...
"        axis off; drawnow;" newline ...
"" newline ...
"        [trialNum, truePos, triggeredBy] = waitForSharedStartClient(fig, cli);" newline ...
"        if trialNum ~= t" newline ...
"            error('Trial mismatch: expected %d, got %d', t, trialNum);" newline ...
"        end" newline ...
"" newline ...
"        lb_draw_trial(fig, truePos, '');" newline ...
"        [resp, rtFirst, rtEnter, editTime] = lb_get_response(fig, truePos, true);" newline ...
"        localDoneTime = datetime('now');" newline ...
"        writeline(cli, sprintf('DONE|%d|CLIENT', t));" newline ...
"" newline ...
"        iti = waitForITIorAbort(cli);" newline ...
"" newline ...
"        row = table({participantID}, {'shared'}, t, truePos, resp, resp-truePos, ..." newline ...
"            rtFirst, rtEnter, editTime, iti, {triggeredBy}, localDoneTime, ..." newline ...
"            'VariableNames', {'participantID','condition','trial','truePosition','response','error', ..." newline ...
"            'RT_firstKey','RT_enter','editingTime','ITI','triggeredBy','timestamp'});" newline ...
"        lb_save_row(localFile, row);" newline ...
"" newline ...
"        clf(fig); set(fig,'Color','k'); axis off; drawnow;" newline ...
"        pause(iti);" newline ...
"    end" newline ...
"" newline ...
"    clf(fig); set(fig,'Color','k');" newline ...
"    text(0.5,0.5,'Finished. Thank you.','Color','w','HorizontalAlignment','center','FontSize',28,'Units','normalized');" newline ...
"    axis off; drawnow;" newline ...
"" newline ...
"catch ME" newline ...
"    try" newline ...
"        writeline(cli, 'ABORT');" newline ...
"    catch" newline ...
"    end" newline ...
"    if isvalid(fig)" newline ...
"        close(fig);" newline ...
"    end" newline ...
"    rethrow(ME);" newline ...
"end" newline ...
"end" newline ...
"" newline ...
"function [trialNum, truePos, triggeredBy] = waitForSharedStartClient(fig, cli)" newline ...
"% Wait for START message from host." newline ...
"% Client may request trial start by pressing SPACE." newline ...
"% Mouse/touchpad input is ignored." newline ...
"" newline ...
"trialNum = NaN;" newline ...
"truePos = NaN;" newline ...
"triggeredBy = '';" newline ...
"spaceAlreadySent = false;" newline ...
"abortTask = false;" newline ...
"set(fig, 'KeyPressFcn', @keyHandler);" newline ...
"" newline ...
"while isnan(trialNum)" newline ...
"    drawnow;" newline ...
"" newline ...
"    if abortTask" newline ...
"        writeline(cli, 'ABORT');" newline ...
"        error('Experiment aborted by CLIENT with ESC.');" newline ...
"    end" newline ...
"" newline ...
"    while cli.NumBytesAvailable > 0" newline ...
"        msg = char(readline(cli));" newline ...
"        if startsWith(msg, 'START')" newline ...
"            parts = split(msg, '|');" newline ...
"            trialNum = str2double(parts{2});" newline ...
"            truePos = str2double(parts{3});" newline ...
"            triggeredBy = parts{4};" newline ...
"            return;" newline ...
"        elseif startsWith(msg, 'FINISHED')" newline ...
"            error('Host finished unexpectedly.');" newline ...
"        elseif startsWith(msg, 'ABORT')" newline ...
"            error('Experiment aborted by HOST.');" newline ...
"        end" newline ...
"    end" newline ...
"" newline ...
"    pause(0.005);" newline ...
"end" newline ...
"" newline ...
"    function keyHandler(~, event)" newline ...
"        switch event.Key" newline ...
"            case 'space'" newline ...
"                if ~spaceAlreadySent" newline ...
"                    writeline(cli, 'SPACE|CLIENT');" newline ...
"                    spaceAlreadySent = true;" newline ...
"                end" newline ...
"            case 'escape'" newline ...
"                abortTask = true;" newline ...
"        end" newline ...
"    end" newline ...
"end" newline ...
"" newline ...
"function iti = waitForITIorAbort(cli)" newline ...
"% Wait for host to send ITI after both participants have responded." newline ...
"iti = NaN;" newline ...
"while isnan(iti)" newline ...
"    drawnow;" newline ...
"    if cli.NumBytesAvailable > 0" newline ...
"        msg = char(readline(cli));" newline ...
"        if startsWith(msg, 'ITI')" newline ...
"            parts = split(msg, '|');" newline ...
"            iti = str2double(parts{2});" newline ...
"            return;" newline ...
"        elseif startsWith(msg, 'ABORT')" newline ...
"            error('Experiment aborted by HOST.');" newline ...
"        elseif startsWith(msg, 'FINISHED')" newline ...
"            iti = 0;" newline ...
"            return;" newline ...
"        end" newline ...
"    end" newline ...
"    pause(0.005);" newline ...
"end" newline ...
"end" newline ...
];
end

function txt = draw_code()
txt = [
"function lb_draw_trial(fig, truePos, typedText)" newline ...
"% Draws the line bisection stimulus." newline ...
"% truePos is in task units from -1000 to +1000." newline ...
"" newline ...
"clf(fig);" newline ...
"set(fig,'Color','k');" newline ...
"ax = axes('Parent',fig,'Color','k','Position',[0 0 1 1]);" newline ...
"axis(ax,[0 1 0 1]);" newline ...
"axis(ax,'off');" newline ...
"hold(ax,'on');" newline ...
"" newline ...
"lineLength = 0.65;" newline ...
"xCenter = 0.5;" newline ...
"y = 0.55;" newline ...
"xLeft = xCenter - lineLength/2;" newline ...
"xRight = xCenter + lineLength/2;" newline ...
"" newline ...
"plot(ax,[xLeft xRight],[y y],'w-','LineWidth',4);" newline ...
"" newline ...
"xTick = xCenter + (truePos/1000)*(lineLength/2);" newline ...
"tickHeight = 0.12;" newline ...
"plot(ax,[xTick xTick],[y-tickHeight/2 y+tickHeight/2],'w-','LineWidth',4);" newline ...
"" newline ...
"text(ax,xLeft,y-0.10,'-1000','Color','w','HorizontalAlignment','center','FontSize',22);" newline ...
"text(ax,xRight,y-0.10,'+1000','Color','w','HorizontalAlignment','center','FontSize',22);" newline ...
"" newline ...
"text(ax,0.5,0.20,'Type your estimate, including + or -, then press ENTER.', ..." newline ...
"    'Color','w','HorizontalAlignment','center','FontSize',20);" newline ...
"" newline ...
"if nargin >= 3 && ~isempty(typedText)" newline ...
"    text(ax,0.5,0.13,typedText,'Color','w','HorizontalAlignment','center','FontSize',28);" newline ...
"end" newline ...
"" newline ...
"drawnow;" newline ...
"end" newline ...
];
end

function txt = response_code()
txt = [
"function [resp, rtFirst, rtEnter, editTime] = lb_get_response(fig, truePos, showTyped)" newline ...
"% Reliable typed keyboard response handler." newline ...
"% Accepts only +, -, digits, Backspace, Enter, Escape." newline ...
"% Ignores mouse and touchpad events." newline ...
"" newline ...
"if nargin < 3" newline ...
"    showTyped = true;" newline ...
"end" newline ...
"" newline ...
"typed = '';" newline ...
"firstKeyTime = NaN;" newline ...
"stimTic = tic;" newline ...
"responseDone = false;" newline ...
"abortTask = false;" newline ...
"" newline ...
"set(fig, 'KeyPressFcn', @keyHandler);" newline ...
"" newline ...
"while ~responseDone" newline ...
"    drawnow;" newline ...
"" newline ...
"    if abortTask" newline ...
"        error('Experiment aborted with ESC.');" newline ...
"    end" newline ...
"" newline ...
"    pause(0.005);" newline ...
"end" newline ...
"" newline ...
"    function keyHandler(~, event)" newline ...
"        key = event.Key;" newline ...
"        nowT = toc(stimTic);" newline ...
"" newline ...
"        if strcmp(key, 'escape')" newline ...
"            abortTask = true;" newline ...
"            return;" newline ...
"        end" newline ...
"" newline ...
"        switch key" newline ...
"            case {'return','enter'}" newline ...
"                rtEnter = nowT;" newline ...
"                if isValidResponse(typed)" newline ...
"                    resp = str2double(typed);" newline ...
"                    if isnan(firstKeyTime)" newline ...
"                        firstKeyTime = rtEnter;" newline ...
"                    end" newline ...
"                    rtFirst = firstKeyTime;" newline ...
"                    editTime = rtEnter - rtFirst;" newline ...
"                    responseDone = true;" newline ...
"                else" newline ...
"                    showInvalid(fig);" newline ...
"                    pause(0.8);" newline ...
"                    typed = '';" newline ...
"                    firstKeyTime = NaN;" newline ...
"                    lb_draw_trial(fig, truePos, '');" newline ...
"                end" newline ...
"" newline ...
"            case 'backspace'" newline ...
"                if isnan(firstKeyTime)" newline ...
"                    firstKeyTime = nowT;" newline ...
"                end" newline ...
"                if ~isempty(typed)" newline ...
"                    typed = typed(1:end-1);" newline ...
"                end" newline ...
"" newline ...
"            case {'add','equal'}" newline ...
"                if isnan(firstKeyTime)" newline ...
"                    firstKeyTime = nowT;" newline ...
"                end" newline ...
"                if isempty(typed)" newline ...
"                    typed = '+';" newline ...
"                end" newline ...
"" newline ...
"            case {'subtract','hyphen'}" newline ...
"                if isnan(firstKeyTime)" newline ...
"                    firstKeyTime = nowT;" newline ...
"                end" newline ...
"                if isempty(typed)" newline ...
"                    typed = '-';" newline ...
"                end" newline ...
"" newline ...
"            otherwise" newline ...
"                digit = keyToDigit(key);" newline ...
"                if ~isempty(digit)" newline ...
"                    if isnan(firstKeyTime)" newline ...
"                        firstKeyTime = nowT;" newline ...
"                    end" newline ...
"                    typed = [typed digit];" newline ...
"                end" newline ...
"        end" newline ...
"" newline ...
"        if showTyped && ~responseDone" newline ...
"            lb_draw_trial(fig, truePos, typed);" newline ...
"        end" newline ...
"    end" newline ...
"end" newline ...
"" newline ...
"function digit = keyToDigit(key)" newline ...
"% Accepts both top-row digits and numpad digits." newline ...
"% To force numpad-only, remove the plain digit cases." newline ...
"digit = '';" newline ...
"switch key" newline ...
"    case {'numpad0','0'}; digit = '0';" newline ...
"    case {'numpad1','1'}; digit = '1';" newline ...
"    case {'numpad2','2'}; digit = '2';" newline ...
"    case {'numpad3','3'}; digit = '3';" newline ...
"    case {'numpad4','4'}; digit = '4';" newline ...
"    case {'numpad5','5'}; digit = '5';" newline ...
"    case {'numpad6','6'}; digit = '6';" newline ...
"    case {'numpad7','7'}; digit = '7';" newline ...
"    case {'numpad8','8'}; digit = '8';" newline ...
"    case {'numpad9','9'}; digit = '9';" newline ...
"end" newline ...
"end" newline ...
"" newline ...
"function tf = isValidResponse(s)" newline ...
"tf = false;" newline ...
"if isempty(s); return; end" newline ...
"if ~(startsWith(s, '+') || startsWith(s, '-'))" newline ...
"    return;" newline ...
"end" newline ...
"numpart = extractAfter(s, 1);" newline ...
"if isempty(numpart); return; end" newline ...
"if any(~isstrprop(numpart,'digit')); return; end" newline ...
"val = str2double(s);" newline ...
"tf = isfinite(val) && val >= -1000 && val <= 1000 && val == round(val);" newline ...
"end" newline ...
"" newline ...
"function showInvalid(fig)" newline ...
"clf(fig);" newline ...
"set(fig,'Color','k');" newline ...
"text(0.5,0.5,'Please enter a signed integer between -1000 and +1000', ..." newline ...
"    'Color','w','HorizontalAlignment','center','FontSize',24,'Units','normalized');" newline ...
"axis off; drawnow;" newline ...
"end" newline ...
];
end

function txt = wait_space_code()
txt = [
"function lb_wait_for_space(fig)" newline ...
"% Waits only for SPACE or ESCAPE." newline ...
"% Ignores mouse/touchpad input." newline ...
"" newline ...
"spacePressed = false;" newline ...
"abortTask = false;" newline ...
"set(fig, 'KeyPressFcn', @keyHandler);" newline ...
"" newline ...
"while ~spacePressed" newline ...
"    drawnow;" newline ...
"" newline ...
"    if abortTask" newline ...
"        error('Experiment aborted with ESC.');" newline ...
"    end" newline ...
"" newline ...
"    pause(0.005);" newline ...
"end" newline ...
"" newline ...
"    function keyHandler(~, event)" newline ...
"        switch event.Key" newline ...
"            case 'space'" newline ...
"                spacePressed = true;" newline ...
"            case 'escape'" newline ...
"                abortTask = true;" newline ...
"        end" newline ...
"    end" newline ...
"end" newline ...
];
end

function txt = save_code()
txt = [
"function lb_save_row(outfile, row)" newline ...
"% Robust row-wise CSV saving." newline ...
"% Creates the output folder if it does not exist." newline ...
"" newline ...
"[folder, ~, ~] = fileparts(outfile);" newline ...
"" newline ...
"if ~isempty(folder) && ~exist(folder, 'dir')" newline ...
"    mkdir(folder);" newline ...
"end" newline ...
"" newline ...
"if exist(outfile, 'file')" newline ...
"    writetable(row, outfile, 'WriteMode', 'append');" newline ...
"else" newline ...
"    writetable(row, outfile);" newline ...
"end" newline ...
"" newline ...
"end" newline ...
];
end
