function create_line_bisection_files()
% Creates MATLAB files for the line bisection experiment.
% No Psychtoolbox required. Uses MATLAB figures + TCP/IP.
% Updated version: robust data-folder handling for individual and shared modes.

writeFile('make_trial_orders.m', make_trial_orders_code());
writeFile('run_line_bisection_individual.m', individual_code());
writeFile('run_line_bisection_shared_host.m', host_code());
writeFile('run_line_bisection_shared_client.m', client_code());
writeFile('lb_draw_trial.m', draw_code());
writeFile('lb_get_response.m', response_code());
writeFile('lb_save_row.m', save_code());

dataDir = fullfile(pwd, 'data');
if ~exist(dataDir, 'dir')
    mkdir(dataDir);
end

disp('Created experiment files successfully.');
disp('Run make_trial_orders first.');
end

function writeFile(fname, txt)
fid = fopen(fname, 'w');
if fid < 0
    error('Could not create %s', fname);
end
fprintf(fid, '%s', txt);
fclose(fid);
end

function txt = make_trial_orders_code()
txt = [
"function orders = make_trial_orders()" newline ...
"% Fixed trial orders for all participants." newline ...
"% Individual and shared orders are different but deterministic." newline ...
"" newline ...
"positions = -900:25:900;   % 73 positions" newline ...
"positions = repmat(positions, 1, 2); % 146 trials" newline ...
"" newline ...
"rng(20260427, 'twister');" newline ...
"orders.individual = positions(randperm(numel(positions)));" newline ...
"" newline ...
"rng(20260428, 'twister');" newline ...
"orders.shared = positions(randperm(numel(positions)));" newline ...
"" newline ...
"save('trial_orders.mat', 'orders');" newline ...
"disp('Saved trial_orders.mat');" newline ...
"end" newline ...
];
end

function txt = individual_code()
txt = [
"function run_line_bisection_individual(participantID)" newline ...
"if nargin < 1 || isempty(participantID)" newline ...
"    participantID = input('Participant/dyad ID, e.g. dyad001_A: ', 's');" newline ...
"end" newline ...
"" newline ...
"if ~exist('trial_orders.mat', 'file')" newline ...
"    make_trial_orders();" newline ...
"end" newline ...
"load('trial_orders.mat', 'orders');" newline ...
"trials = orders.individual;" newline ...
"" newline ...
"dataDir = fullfile(pwd, 'data');" newline ...
"if ~exist(dataDir, 'dir')" newline ...
"    mkdir(dataDir);" newline ...
"end" newline ...
"outfile = fullfile(dataDir, [participantID '_individual.csv']);" newline ...
"" newline ...
"fig = figure('Color','k','MenuBar','none','ToolBar','none','NumberTitle','off', ..." newline ...
"    'Name','Line Bisection - Individual','KeyPressFcn',@(~,~)[]);" newline ...
"set(fig, 'WindowState', 'maximized');" newline ...
"drawnow;" newline ...
"" newline ...
"for t = 1:numel(trials)" newline ...
"    truePos = trials(t);" newline ...
"    clf(fig);" newline ...
"    text(0.5,0.5,sprintf('Trial %d of %d\n\nPress SPACE to start',t,numel(trials)), ..." newline ...
"        'Color','w','HorizontalAlignment','center','FontSize',24,'Units','normalized');" newline ...
"    axis off;" newline ...
"    waitforbuttonpress;" newline ...
"    while ~strcmp(get(fig,'CurrentCharacter'),' ')" newline ...
"        waitforbuttonpress;" newline ...
"    end" newline ...
"" newline ...
"    lb_draw_trial(fig, truePos, '');" newline ...
"    [resp, rtFirst, rtEnter, editTime] = lb_get_response(fig, truePos, true);" newline ...
"" newline ...
"    row = table({participantID}, {'individual'}, t, truePos, resp, resp-truePos, ..." newline ...
"        rtFirst, rtEnter, editTime, NaN, {''}, datetime('now'), ..." newline ...
"        'VariableNames', {'participantID','condition','trial','truePosition','response','error', ..." newline ...
"        'RT_firstKey','RT_enter','editingTime','ITI','triggeredBy','timestamp'});" newline ...
"    lb_save_row(outfile, row);" newline ...
"" newline ...
"    iti = 0.3 + rand()*0.2;" newline ...
"    clf(fig); set(fig,'Color','k'); axis off; drawnow;" newline ...
"    pause(iti);" newline ...
"end" newline ...
"" newline ...
"clf(fig);" newline ...
"text(0.5,0.5,'Finished. Thank you.','Color','w','HorizontalAlignment','center','FontSize',28,'Units','normalized');" newline ...
"axis off;" newline ...
"end" newline ...
];
end

function txt = host_code()
txt = [
"function run_line_bisection_shared_host(dyadID, participantID, port)" newline ...
"if nargin < 1 || isempty(dyadID); dyadID = input('Dyad ID, e.g. dyad001: ', 's'); end" newline ...
"if nargin < 2 || isempty(participantID); participantID = [dyadID '_A']; end" newline ...
"if nargin < 3 || isempty(port); port = 50000; end" newline ...
"" newline ...
"if ~exist('trial_orders.mat', 'file'); make_trial_orders(); end" newline ...
"load('trial_orders.mat', 'orders');" newline ...
"trials = orders.shared;" newline ...
"" newline ...
"dataDir = fullfile(pwd, 'data');" newline ...
"if ~exist(dataDir, 'dir')" newline ...
"    mkdir(dataDir);" newline ...
"end" newline ...
"localFile = fullfile(dataDir, [participantID '_shared.csv']);" newline ...
"syncFile = fullfile(dataDir, [dyadID '_shared_sync.csv']);" newline ...
"" newline ...
"disp(['Starting TCP server on port ' num2str(port)]);" newline ...
"srv = tcpserver('0.0.0.0', port, 'Timeout', 60);" newline ...
"configureTerminator(srv, 'LF');" newline ...
"disp('Waiting for client...');" newline ...
"while srv.Connected == 0; pause(0.1); end" newline ...
"disp('Client connected.');" newline ...
"writeline(srv, 'HELLO_FROM_HOST');" newline ...
"" newline ...
"fig = figure('Color','k','MenuBar','none','ToolBar','none','NumberTitle','off', ..." newline ...
"    'Name','Line Bisection - Shared Host','KeyPressFcn',@(~,~)[]);" newline ...
"set(fig, 'WindowState', 'maximized'); drawnow;" newline ...
"" newline ...
"for t = 1:numel(trials)" newline ...
"    truePos = trials(t);" newline ...
"    clf(fig);" newline ...
"    text(0.5,0.5,sprintf(['Trial %d of %d\n\nYou and your partner will see the same line.\n' ..." newline ...
"        'Work silently and enter only your own estimate.\n\nEither participant may press SPACE to start.'], t, numel(trials)), ..." newline ...
"        'Color','w','HorizontalAlignment','center','FontSize',22,'Units','normalized');" newline ...
"    axis off; drawnow;" newline ...
"" newline ...
"    triggeredBy = waitForSharedSpaceHost(fig, srv);" newline ...
"    msg = sprintf('START|%d|%d|%s', t, truePos, triggeredBy);" newline ...
"    writeline(srv, msg);" newline ...
"" newline ...
"    lb_draw_trial(fig, truePos, '');" newline ...
"    [resp, rtFirst, rtEnter, editTime] = lb_get_response(fig, truePos, true);" newline ...
"    localDoneTime = datetime('now');" newline ...
"    writeline(srv, sprintf('DONE|%d|HOST', t));" newline ...
"" newline ...
"    waitForClientDone(srv, t);" newline ...
"" newline ...
"    row = table({participantID}, {'shared'}, t, truePos, resp, resp-truePos, ..." newline ...
"        rtFirst, rtEnter, editTime, NaN, {triggeredBy}, localDoneTime, ..." newline ...
"        'VariableNames', {'participantID','condition','trial','truePosition','response','error', ..." newline ...
"        'RT_firstKey','RT_enter','editingTime','ITI','triggeredBy','timestamp'});" newline ...
"    lb_save_row(localFile, row);" newline ...
"" newline ...
"    syncRow = table({dyadID}, t, truePos, {triggeredBy}, datetime('now'), ..." newline ...
"        'VariableNames', {'dyadID','trial','truePosition','triggeredBy','timestamp'});" newline ...
"    lb_save_row(syncFile, syncRow);" newline ...
"" newline ...
"    iti = 0.3 + rand()*0.2;" newline ...
"    writeline(srv, sprintf('ITI|%.3f', iti));" newline ...
"    clf(fig); set(fig,'Color','k'); axis off; drawnow; pause(iti);" newline ...
"end" newline ...
"" newline ...
"writeline(srv, 'FINISHED');" newline ...
"clf(fig); text(0.5,0.5,'Finished. Thank you.','Color','w','HorizontalAlignment','center','FontSize',28,'Units','normalized'); axis off;" newline ...
"end" newline ...
"" newline ...
"function triggeredBy = waitForSharedSpaceHost(fig, srv)" newline ...
"triggeredBy = '';" newline ...
"set(fig, 'CurrentCharacter', char(0));" newline ...
"while isempty(triggeredBy)" newline ...
"    drawnow;" newline ...
"    ch = get(fig, 'CurrentCharacter');" newline ...
"    if strcmp(ch, ' ')" newline ...
"        triggeredBy = 'HOST';" newline ...
"        set(fig, 'CurrentCharacter', char(0));" newline ...
"        return;" newline ...
"    end" newline ...
"    if srv.NumBytesAvailable > 0" newline ...
"        msg = char(readline(srv));" newline ...
"        if startsWith(msg, 'SPACE')" newline ...
"            triggeredBy = 'CLIENT';" newline ...
"            return;" newline ...
"        end" newline ...
"    end" newline ...
"    pause(0.01);" newline ...
"end" newline ...
"end" newline ...
"" newline ...
"function waitForClientDone(srv, trialNum)" newline ...
"while true" newline ...
"    if srv.NumBytesAvailable > 0" newline ...
"        msg = char(readline(srv));" newline ...
"        if startsWith(msg, sprintf('DONE|%d|CLIENT', trialNum))" newline ...
"            return;" newline ...
"        end" newline ...
"    end" newline ...
"    pause(0.01);" newline ...
"end" newline ...
"end" newline ...
];
end

function txt = client_code()
txt = [
"function run_line_bisection_shared_client(dyadID, participantID, hostIP, port)" newline ...
"if nargin < 1 || isempty(dyadID); dyadID = input('Dyad ID, e.g. dyad001: ', 's'); end" newline ...
"if nargin < 2 || isempty(participantID); participantID = [dyadID '_B']; end" newline ...
"if nargin < 3 || isempty(hostIP); hostIP = input('Host IP address: ', 's'); end" newline ...
"if nargin < 4 || isempty(port); port = 50000; end" newline ...
"" newline ...
"if ~exist('trial_orders.mat', 'file'); make_trial_orders(); end" newline ...
"load('trial_orders.mat', 'orders');" newline ...
"trials = orders.shared;" newline ...
"" newline ...
"dataDir = fullfile(pwd, 'data');" newline ...
"if ~exist(dataDir, 'dir')" newline ...
"    mkdir(dataDir);" newline ...
"end" newline ...
"localFile = fullfile(dataDir, [participantID '_shared.csv']);" newline ...
"" newline ...
"disp(['Connecting to host ' hostIP ':' num2str(port)]);" newline ...
"cli = tcpclient(hostIP, port, 'Timeout', 60);" newline ...
"configureTerminator(cli, 'LF');" newline ...
"pause(0.5);" newline ...
"" newline ...
"fig = figure('Color','k','MenuBar','none','ToolBar','none','NumberTitle','off', ..." newline ...
"    'Name','Line Bisection - Shared Client','KeyPressFcn',@(~,~)[]);" newline ...
"set(fig, 'WindowState', 'maximized'); drawnow;" newline ...
"" newline ...
"for t = 1:numel(trials)" newline ...
"    clf(fig);" newline ...
"    text(0.5,0.5,sprintf(['Trial %d of %d\n\nYou and your partner will see the same line.\n' ..." newline ...
"        'Work silently and enter only your own estimate.\n\nEither participant may press SPACE to start.'], t, numel(trials)), ..." newline ...
"        'Color','w','HorizontalAlignment','center','FontSize',22,'Units','normalized');" newline ...
"    axis off; drawnow;" newline ...
"" newline ...
"    waitForStartOrSendSpace(fig, cli);" newline ...
"    [trialNum, truePos, triggeredBy] = waitForStartMessage(cli);" newline ...
"    if trialNum ~= t" newline ...
"        error('Trial mismatch: expected %d, got %d', t, trialNum);" newline ...
"    end" newline ...
"" newline ...
"    lb_draw_trial(fig, truePos, '');" newline ...
"    [resp, rtFirst, rtEnter, editTime] = lb_get_response(fig, truePos, true);" newline ...
"    writeline(cli, sprintf('DONE|%d|CLIENT', t));" newline ...
"" newline ...
"    row = table({participantID}, {'shared'}, t, truePos, resp, resp-truePos, ..." newline ...
"        rtFirst, rtEnter, editTime, NaN, {triggeredBy}, datetime('now'), ..." newline ...
"        'VariableNames', {'participantID','condition','trial','truePosition','response','error', ..." newline ...
"        'RT_firstKey','RT_enter','editingTime','ITI','triggeredBy','timestamp'});" newline ...
"    lb_save_row(localFile, row);" newline ...
"" newline ...
"    iti = waitForITI(cli);" newline ...
"    clf(fig); set(fig,'Color','k'); axis off; drawnow; pause(iti);" newline ...
"end" newline ...
"" newline ...
"clf(fig); text(0.5,0.5,'Finished. Thank you.','Color','w','HorizontalAlignment','center','FontSize',28,'Units','normalized'); axis off;" newline ...
"end" newline ...
"" newline ...
"function waitForStartOrSendSpace(fig, cli)" newline ...
"set(fig, 'CurrentCharacter', char(0));" newline ...
"sent = false;" newline ...
"while true" newline ...
"    drawnow;" newline ...
"    if cli.NumBytesAvailable > 0" newline ...
"        return;" newline ...
"    end" newline ...
"    ch = get(fig, 'CurrentCharacter');" newline ...
"    if strcmp(ch, ' ') && ~sent" newline ...
"        writeline(cli, 'SPACE|CLIENT');" newline ...
"        sent = true;" newline ...
"        set(fig, 'CurrentCharacter', char(0));" newline ...
"    end" newline ...
"    pause(0.01);" newline ...
"end" newline ...
"end" newline ...
"" newline ...
"function [trialNum, truePos, triggeredBy] = waitForStartMessage(cli)" newline ...
"while true" newline ...
"    if cli.NumBytesAvailable > 0" newline ...
"        msg = char(readline(cli));" newline ...
"        if startsWith(msg, 'START')" newline ...
"            parts = split(msg, '|');" newline ...
"            trialNum = str2double(parts{2});" newline ...
"            truePos = str2double(parts{3});" newline ...
"            triggeredBy = parts{4};" newline ...
"            return;" newline ...
"        end" newline ...
"    end" newline ...
"    pause(0.01);" newline ...
"end" newline ...
"end" newline ...
"" newline ...
"function iti = waitForITI(cli)" newline ...
"iti = 0.4;" newline ...
"while true" newline ...
"    if cli.NumBytesAvailable > 0" newline ...
"        msg = char(readline(cli));" newline ...
"        if startsWith(msg, 'ITI')" newline ...
"            parts = split(msg, '|');" newline ...
"            iti = str2double(parts{2});" newline ...
"            return;" newline ...
"        elseif startsWith(msg, 'FINISHED')" newline ...
"            return;" newline ...
"        end" newline ...
"    end" newline ...
"    pause(0.01);" newline ...
"end" newline ...
"end" newline ...
];
end

function txt = draw_code()
txt = [
"function lb_draw_trial(fig, truePos, typedText)" newline ...
"% Draws the line-bisection stimulus." newline ...
"% truePos is in -1000..1000 units." newline ...
"" newline ...
"clf(fig);" newline ...
"set(fig,'Color','k');" newline ...
"ax = axes('Parent',fig,'Color','k','Position',[0 0 1 1]);" newline ...
"axis(ax,[0 1 0 1]); axis(ax,'off'); hold(ax,'on');" newline ...
"" newline ...
"lineLength = 0.65;" newline ...
"xCenter = 0.5;" newline ...
"y = 0.55;" newline ...
"xLeft = xCenter - lineLength/2;" newline ...
"xRight = xCenter + lineLength/2;" newline ...
"" newline ...
"plot(ax,[xLeft xRight],[y y],'w-','LineWidth',4);" newline ...
"" newline ...
"xTick = xCenter + (truePos/1000)*(lineLength/2);" newline ...
"tickHeight = 0.12;" newline ...
"plot(ax,[xTick xTick],[y-tickHeight/2 y+tickHeight/2],'w-','LineWidth',4);" newline ...
"" newline ...
"text(ax,xLeft,y-0.10,'-1000','Color','w','HorizontalAlignment','center','FontSize',22);" newline ...
"text(ax,xRight,y-0.10,'+1000','Color','w','HorizontalAlignment','center','FontSize',22);" newline ...
"" newline ...
"text(ax,0.5,0.20,'Type your estimate, including + or -, then press ENTER.', ..." newline ...
"    'Color','w','HorizontalAlignment','center','FontSize',20);" newline ...
"" newline ...
"if nargin >= 3 && ~isempty(typedText)" newline ...
"    text(ax,0.5,0.13,typedText,'Color','w','HorizontalAlignment','center','FontSize',28);" newline ...
"end" newline ...
"" newline ...
"drawnow;" newline ...
"end" newline ...
];
end

function txt = response_code()
txt = [
"function [resp, rtFirst, rtEnter, editTime] = lb_get_response(fig, truePos, showTyped)" newline ...
"% Typed signed integer response. Positive numbers must start with +." newline ...
"if nargin < 3; showTyped = true; end" newline ...
"" newline ...
"typed = '';" newline ...
"firstKeyTime = NaN;" newline ...
"stimTic = tic;" newline ...
"" newline ...
"while true" newline ...
"    waitforbuttonpress;" newline ...
"    ch = get(fig,'CurrentCharacter');" newline ...
"    nowT = toc(stimTic);" newline ...
"" newline ...
"    if isnan(firstKeyTime)" newline ...
"        firstKeyTime = nowT;" newline ...
"    end" newline ...
"" newline ...
"    if double(ch) == 13 || double(ch) == 10" newline ...
"        rtEnter = nowT;" newline ...
"        if isValidResponse(typed)" newline ...
"            resp = str2double(typed);" newline ...
"            rtFirst = firstKeyTime;" newline ...
"            editTime = rtEnter - rtFirst;" newline ...
"            return;" newline ...
"        else" newline ...
"            showInvalid(fig);" newline ...
"            pause(0.8);" newline ...
"            typed = '';" newline ...
"            firstKeyTime = NaN;" newline ...
"            lb_draw_trial(fig, truePos, '');" newline ...
"        end" newline ...
"    elseif double(ch) == 8" newline ...
"        if ~isempty(typed)" newline ...
"            typed = typed(1:end-1);" newline ...
"        end" newline ...
"    elseif ismember(ch, ['0':'9' '+' '-'])" newline ...
"        typed = [typed ch];" newline ...
"    end" newline ...
"" newline ...
"    if showTyped" newline ...
"        lb_draw_trial(fig, truePos, typed);" newline ...
"    end" newline ...
"end" newline ...
"end" newline ...
"" newline ...
"function tf = isValidResponse(s)" newline ...
"tf = false;" newline ...
"if isempty(s); return; end" newline ...
"if startsWith(s, '+')" newline ...
"    numpart = extractAfter(s,1);" newline ...
"    if isempty(numpart); return; end" newline ...
"elseif startsWith(s, '-')" newline ...
"    numpart = extractAfter(s,1);" newline ...
"    if isempty(numpart); return; end" newline ...
"else" newline ...
"    return;" newline ...
"end" newline ...
"if any(~isstrprop(numpart,'digit')); return; end" newline ...
"val = str2double(s);" newline ...
"tf = isfinite(val) && val >= -1000 && val <= 1000 && val == round(val);" newline ...
"end" newline ...
"" newline ...
"function showInvalid(fig)" newline ...
"clf(fig); set(fig,'Color','k');" newline ...
"text(0.5,0.5,'Please enter a number between -1000 and 1000', ..." newline ...
"    'Color','w','HorizontalAlignment','center','FontSize',24,'Units','normalized');" newline ...
"axis off; drawnow;" newline ...
"end" newline ...
];
end

function txt = save_code()
txt = [
"function lb_save_row(outfile, row)" newline ...
"% Make sure the output folder exists before writing the file." newline ...
"[folder, ~, ~] = fileparts(outfile);" newline ...
"" newline ...
"if ~isempty(folder) && ~exist(folder, 'dir')" newline ...
"    mkdir(folder);" newline ...
"end" newline ...
"" newline ...
"% Save row. If the file exists, append. If not, create it." newline ...
"if exist(outfile, 'file')" newline ...
"    writetable(row, outfile, 'WriteMode', 'append');" newline ...
"else" newline ...
"    writetable(row, outfile);" newline ...
"end" newline ...
"" newline ...
"end" newline ...
];
end